
from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

class Ui_MWClip(object):
  def setupUi(self, MWClip):
    MWClip.setObjectName("MWClip")
    MWClip.resize(800, 450)
    MWClip.setMinimumSize(QtCore.QSize(800, 450))
    MWClip.setMaximumSize(QtCore.QSize(800, 450))
    MWClip.setFocusPolicy(QtCore.Qt.ClickFocus)

    fontMain = QtGui.QFont()
    fontMain.setPointSize(8)
    fontMain.setBold(False)
    fontMain.setWeight(50)
    fontBold = QtGui.QFont()
    fontBold.setBold(True)
    fontBold.setWeight(75)

    self.groupBox_1 = QtWidgets.QGroupBox(MWClip)
    self.groupBox_1.setGeometry(QtCore.QRect(10, 10, 450, 130))
    self.groupBox_1.setFont(fontMain)
    self.groupBox_1.setObjectName(_fromUtf8("groupBox_1"))
    self.cbxShapeInput = QtWidgets.QComboBox(self.groupBox_1)
    self.cbxShapeInput.setGeometry(QtCore.QRect(10, 40, 390, 20))
    self.cbxShapeInput.setObjectName(_fromUtf8("cbxShapeInput"))
    self.label_1 = QtWidgets.QLabel(self.groupBox_1)
    self.label_1.setGeometry(QtCore.QRect(10, 20, 200, 20))
    self.label_1.setFont(fontBold)
    self.label_1.setObjectName(_fromUtf8("label_1"))
    self.btnSearchShapeInput = QtWidgets.QPushButton(self.groupBox_1)
    self.btnSearchShapeInput.setGeometry(QtCore.QRect(410, 40, 30, 20))
    self.btnSearchShapeInput.setObjectName(_fromUtf8("btnSearchShapeInput"))
    self.label_2 = QtWidgets.QLabel(self.groupBox_1)
    self.label_2.setGeometry(QtCore.QRect(10, 70, 200, 20))
    self.label_2.setFont(fontBold)
    self.label_2.setObjectName(_fromUtf8("label_2"))
    self.cbxFieldData = QtWidgets.QComboBox(self.groupBox_1)
    self.cbxFieldData.setGeometry(QtCore.QRect(220, 70, 220, 20))
    self.cbxFieldData.setObjectName(_fromUtf8("cbxFieldData"))
    self.label_3 = QtWidgets.QLabel(self.groupBox_1)
    self.label_3.setGeometry(QtCore.QRect(10, 100, 200, 20))
    self.label_3.setFont(fontBold)
    self.label_3.setObjectName(_fromUtf8("label_3"))
    self.cbxFieldGroup = QtWidgets.QComboBox(self.groupBox_1)
    self.cbxFieldGroup.setGeometry(QtCore.QRect(220, 100, 220, 20))
    self.cbxFieldGroup.setObjectName(_fromUtf8("cbxFieldGroup"))

    self.groupBox_2 = QtWidgets.QGroupBox(MWClip)
    self.groupBox_2.setGeometry(QtCore.QRect(10, 150, 450, 70))
    self.groupBox_2.setFont(fontMain)
    self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
    self.label_4 = QtWidgets.QLabel(self.groupBox_2)
    self.label_4.setGeometry(QtCore.QRect(10, 20, 200, 20))
    self.label_4.setFont(fontBold)
    self.label_4.setObjectName(_fromUtf8("label_4"))
    self.cbxShapeOutput = QtWidgets.QComboBox(self.groupBox_2)
    self.cbxShapeOutput.setGeometry(QtCore.QRect(10, 40, 390, 20))
    self.cbxShapeOutput.setObjectName(_fromUtf8("cbxShapeOutput"))
    self.btnSearchShapeOutput = QtWidgets.QToolButton(self.groupBox_2)
    self.btnSearchShapeOutput.setGeometry(QtCore.QRect(410, 40, 30, 20))
    self.btnSearchShapeOutput.setObjectName(_fromUtf8("btnSearchShapeOutput"))

    self.groupBox_3 = QtWidgets.QGroupBox(MWClip)
    self.groupBox_3.setEnabled(True)
    self.groupBox_3.setGeometry(QtCore.QRect(10, 230, 450, 80))
    self.groupBox_3.setFont(fontMain)
    self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
    self.label_5 = QtWidgets.QLabel(self.groupBox_3)
    self.label_5.setGeometry(QtCore.QRect(10, 20, 200, 20))
    self.label_5.setFont(fontBold)
    self.label_5.setObjectName(_fromUtf8("label_5"))
    self.label_6 = QtWidgets.QLabel(self.groupBox_3)
    self.label_6.setGeometry(QtCore.QRect(10, 50, 200, 20))
    self.label_6.setFont(fontBold)
    self.label_6.setObjectName(_fromUtf8("label_6"))
    self.cbxFieldJoinInput = QtWidgets.QComboBox(self.groupBox_3)
    self.cbxFieldJoinInput.setGeometry(QtCore.QRect(220, 20, 220, 20))
    self.cbxFieldJoinInput.setObjectName(_fromUtf8("cbxFieldJoinInput"))
    self.cbxFieldJoinOutput = QtWidgets.QComboBox(self.groupBox_3)
    self.cbxFieldJoinOutput.setGeometry(QtCore.QRect(220, 50, 220, 20))
    self.cbxFieldJoinOutput.setObjectName(_fromUtf8("cbxFieldJoinOutput"))

    self.groupBox_4 = QtWidgets.QGroupBox(MWClip)
    self.groupBox_4.setGeometry(QtCore.QRect(10, 320, 450, 80))
    self.groupBox_4.setFont(fontMain)
    self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
    self.chkNewField = QtWidgets.QCheckBox(self.groupBox_4)
    self.chkNewField.setGeometry(QtCore.QRect(10, 20, 200, 20))
    self.chkNewField.setFont(fontBold)
    self.chkNewField.setObjectName(_fromUtf8("chkNewField"))
    self.chkUpdateField = QtWidgets.QCheckBox(self.groupBox_4)
    self.chkUpdateField.setGeometry(QtCore.QRect(10, 50, 200, 20))
    self.chkUpdateField.setFont(fontBold)
    self.chkUpdateField.setObjectName(_fromUtf8("chkUpdateField"))
    self.cbxUpdateField = QtWidgets.QComboBox(self.groupBox_4)
    self.cbxUpdateField.setGeometry(QtCore.QRect(220, 50, 220, 20))
    self.cbxUpdateField.setObjectName(_fromUtf8("cbxUpdateField"))
    self.grpNewField = QtWidgets.QGroupBox(self.groupBox_4)
    self.grpNewField.setGeometry(QtCore.QRect(220, 20, 220, 20))
    self.grpNewField.setTitle(_fromUtf8(""))
    self.grpNewField.setObjectName(_fromUtf8("grpNewField"))
    self.label_7 = QtWidgets.QLabel(self.grpNewField)
    self.label_7.setGeometry(QtCore.QRect(5, 0, 50, 20))
    self.label_7.setFont(fontBold)
    self.label_7.setObjectName(_fromUtf8("label_7"))
    self.txtNewField = QtWidgets.QLineEdit(self.grpNewField)
    self.txtNewField.setGeometry(QtCore.QRect(60, 0, 160, 20))
    self.txtNewField.setObjectName(_fromUtf8("txtNewField"))
    
    self.btnRunMain = QtWidgets.QDialogButtonBox(MWClip)
    self.btnRunMain.setGeometry(QtCore.QRect(10, 410, 150, 30))
    # font = QtGui.QFont()
    # font.setPointSize(12)
    # self.btnRunMain.setFont(font)
    self.btnRunMain.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
    self.btnRunMain.setCenterButtons(True)
    self.btnRunMain.setObjectName(_fromUtf8("btnRunMain"))

    self.prgProgresBarMain = QtWidgets.QProgressBar(MWClip)
    self.prgProgresBarMain.setGeometry(QtCore.QRect(170, 410, 620, 30))
    self.prgProgresBarMain.setProperty("value", 0)
    self.prgProgresBarMain.setObjectName(_fromUtf8("prgProgresBarMain"))

    self.graphicsViewMain = QtWidgets.QGraphicsView(MWClip)
    self.graphicsViewMain.setGeometry(QtCore.QRect(470, 10, 320, 390))
    self.graphicsViewMain.setObjectName(_fromUtf8("graphicsViewMain"))

    self.retranslateUi(MWClip)
    QtCore.QMetaObject.connectSlotsByName(MWClip)

  def retranslateUi(self, MWClip):
    _translate = QtCore.QCoreApplication.translate
    MWClip.setWindowTitle(_translate("MWClip", "GiniLorenz"))
    self.groupBox_1.setTitle(_translate("dlgGiniLorenz", "Parámetros de entrada", None))
    self.label_1.setText(_translate("dlgGiniLorenz", "Selecciona el shape con datos:", None))
    self.btnSearchShapeInput.setText(_translate("dlgGiniLorenz", "...", None))
    self.label_2.setText(_translate("dlgGiniLorenz", "Campo de entrada (poblacion):", None))
    self.label_3.setText(_translate("dlgGiniLorenz", "Campo de separación por grupo:", None))
    
    self.groupBox_2.setTitle(_translate("dlgGiniLorenz", "Guardar datos en...", None))
    self.label_4.setText(_translate("dlgGiniLorenz", "Selecciona el shape destino:", None))
    self.btnSearchShapeOutput.setText(_translate("dlgGiniLorenz", "...", None))

    self.groupBox_3.setTitle(_translate("dlgGiniLorenz", "Relacionar datos por:", None))
    self.label_5.setText(_translate("dlgGiniLorenz", "Campo 1 (capa de entrada):", None))
    self.label_6.setText(_translate("dlgGiniLorenz", "Campo 2 (capa de destino):", None))

    self.groupBox_4.setTitle(_translate("dlgGiniLorenz", "Resultado (capa destino)", None))
    self.chkNewField.setText(_translate("dlgGiniLorenz", "Crear campo nuevo (decimal): ", None))
    self.chkUpdateField.setText(_translate("dlgGiniLorenz", "Actualizar capo existente:", None))
    self.label_7.setText(_translate("dlgGiniLorenz", "Nombre:", None))

if __name__ == "__main__":
  import sys
  app = QtWidgets.QApplication(sys.argv)
  MWClip = QtWidgets.QMainWindow()
  ui = Ui_MWClip()
  ui.setupUi(MWClip)
  MWClip.show()
  sys.exit(app.exec_())

#import resources_rc